name: Test env variable

# This workflow is triggered on pushes to master
on:
  push:
    branches:
      - master

jobs:
  test_env_variable:
    runs-on: ubuntu-latest
    steps:
      - name: Check environment variable 1
        env:
          TEST_ENV_VARIABLE_1: my_var_1
        run: |
          echo "The value of the environment variable is: ${{ env.TEST_ENV_VARIABLE_1 }}"
      - name: Check environment variable 2
        env:
          TEST_ENV_VARIABLE_2: my_var_2
        run: |
          echo "The value of the environment variable is: ${{ env.TEST_ENV_VARIABLE_2 }}"
